services:
  - type: web
    name: lopenling-editor
    env: node
    plan: starter
    # Update the following line with your Strapi GitHub repo
    repo: https://github.com/lopenling/editor
    branch: main
    buildCommand: npm ci --production=false && npm run build && npm prune --production
    startCommand: npx prisma migrate deploy && npm run start
    envVars:
      - key: NODE_VERSION
        value: ~18.18.0
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: lopenling-editor-pg
          property: connectionString

databases:
  - name: lopenling-editor-pg
    plan: starter
