name = "lopenling-app"

workers_dev = true
main = "./build/index.js"
account_id = "542d340d71d90c60471c8a30e3f7c65e"
compatibility_date = "2022-11-30"
compatibility_flags = ["streams_enable_constructors"]

[site]
bucket = "./public"

[[kv_namespaces]]
binding = "SESSIONS"
id = "75bd4d2a632c48ca8611a84394024d3d"
preview_id = "964fdd4a3eb54a04bfc825390edf6d4b"
