name = "lopenling"

workers_dev = true
main = "./build/index.js"
account_id="542d340d71d90c60471c8a30e3f7c65e"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2022-04-05"

kv_namespaces = [
  { binding = "SESSIONS", preview_id = "32ed6268dab1406ebad067d982980857",id = "32ed6268dab1406ebad067d982980857" }
]
[site]
  bucket = "./public"



[vars]
 DISCOURSE_API_KEY="69692ed5e365396b9ae17acd63334b444cf07ab1b8c0f43a9e67764fb7a31b02"

   DISCOURSE_SSO_REDIRECT='https://lopenling.openpecha.workers.dev/sso/login'
   DISCOURSE_SSO_LOGIN_URL='https://lopenling.org/session/sso_provider'
   DISCOURSE_SSO_SIGNUP_URL='https://lopenling.org/signup'
   ORIGIN_LOCATION="https://lopenling.openpecha.workers.dev"
   DISCOURSE_SITE='https://lopenling.org'
   DISCOURSE_QA_CATEGORY_ID=65
