name = "lopenling"

workers_dev = true
main = "./build/index.js"
account_id="542d340d71d90c60471c8a30e3f7c65e"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2022-04-05"

kv_namespaces = [
  { binding = "SESSIONS", id = "8ab5fe4256d84a1c99a9753bf512a723" }  
]
[site]
  bucket = "./public"

[build]
  command = "npm run build"

[vars]
DATABASE_URL = "prisma://aws-eu-central-1.prisma-data.com/?api_key=Dj9J47_6-lEx_DTaxInxJSd5b6bbFuGkdUBA11-oxYI-5aAGZaqjPSY1bxeWAGgc"
DISCOURSE_SSO_REDIRECT='http://localhost:8787/sso/login'
DISCOURSE_SSO_LOGIN_URL='https://lopenling.org/session/sso_provider'
DISCOURSE_SSO_SIGNUP_URL='https://lopenling.org/signup'
ORIGIN_LOCATION="http://localhost:8787"
DISCOURSE_SITE='https://lopenling.org'
DISCOURSE_API_KEY="69692ed5e365396b9ae17acd63334b444cf07ab1b8c0f43a9e67764fb7a31b02"
DISCOURSE_QA_CATEGORY_ID="65"