name = "lopenling"

workers_dev = true
main = "./build/index.js"
account_id="542d340d71d90c60471c8a30e3f7c65e"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2022-04-05"
compatibility_flags = ["streams_enable_constructors"]

[site]
bucket = "./public"

[[kv_namespaces]]
binding = "SESSIONS"
id = "ac731a42acec4a3a84a81e86119a0c7d"
preview_id = "cafd863b818c4062a021975a54a3a695"

[vars]
DATABASE_URL="prisma://aws-eu-central-1.prisma-data.com/?api_key=04ZIkgiUxg1fLrnH2Hi24opBra5qWr7T6uYnjMA1DonAPQRaQU2IR-7Wq18p6pCn"
DISCOURSE_API_KEY="69692ed5e365396b9ae17acd63334b444cf07ab1b8c0f43a9e67764fb7a31b02"
DISCOURSE_SSO_REDIRECT='https://lopenling.openpecha.workers.dev/sso/login'
DISCOURSE_SSO_LOGIN_URL='https://lopenling.org/session/sso_provider'
DISCOURSE_SSO_SIGNUP_URL='https://lopenling.org/signup'
ORIGIN_LOCATION="https://lopenling.openpecha.workers.dev"
DISCOURSE_SITE='https://lopenling.org'
DISCOURSE_QA_CATEGORY_ID=65
