name = "lopenling-app"

workers_dev = true
main = "./build/index.js"
account_id ="542d340d71d90c60471c8a30e3f7c65e"
compatibility_date = "2022-04-05"

[site]
bucket = "./public"

[[kv_namespaces]]
binding = "SESSIONS"
id = "b8a947c3f76646e59296f4569b720027"
preview_id = "604c7bc6c9ce4391b069ff0e23ffce22"
